### ISSUE TITLE
create a schedule plugin

### ISSUE THREAD

**Issue by WillGross** [WillGross/STARRS#23]
schedule plugin must have 3 versions, a rider version which only displays if there is a jitney scheduled to be running at a given time on a given day (to be used on the main user page), a driver version which allows the driver to view the schedule including information such as who is driving what shift and what vehicle they are driving, and a security version that allows for the scheduling and canceling of all drivers for all shifts. the plugin must display on the page in a calendar like form  so that it is intuitive when things are happening. if there is a shift without a driver, keep the cell for that shift empty, but still display.

**Comment by Jatower** [comment]
@WillGross in your original comment you said that shifts without drivers should leave that cell blank, but the database won't allow for a shift to be entered without a driver, because it is a foreign key to another table. I can't see a way around this without restructuring the database - should we do that or just leave it so that any shift will have to have an associated driver? I believe it should be possible to switch drivers as long as there is still a value entered.

**Comment by Jatower** [comment]
Additionally, this might change the functionality of the security version of the plugin, so that they must enter an entirely new shift with driver information or switch drivers for an existing shift, rather than scheduling drivers to existing shifts.

**Comment by Jatower** [comment]
However I have finished the driver version of the plugin, which can now be specified with a shortcode argument.

**Comment by Jatower** [comment]
Split security functionality to add/remove shifts to a separate plugin - This plugin will now be used exclusively to display shift information for drivers or general users
